version: '3'

services:
    mysql:
        container_name: "${PROJ_NAME}__mysql"
        image: mysql:5.7
#        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        restart: always
        ports:
            - 3307:3306
        volumes:
            - ./docker/var/mysql:/var/lib/mysql
            - ./docker/dump:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_DATABASE: "${PROJ_NAME}_db"
            MYSQL_USER: "${PROJ_NAME}_user"
            MYSQL_PASSWORD: "secret"
    php:
        container_name: "${PROJ_NAME}_php"
        build: docker/php
#        user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
        volumes:
            - ./docker/php/z-overrides.ini:/usr/local/etc/php/conf.d/z-overrides.ini
            - ./:/var/www/html
        depends_on:
            - mysql

    nginx:
        container_name: "${PROJ_NAME}_nginx"
        build: ./docker/nginx
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        ports:
            - "8000:80"
        depends_on:
            - php

    phpmyadmin:
        container_name: "${PROJ_NAME}_phpmyadmin"
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: "secret"
        depends_on:
            - mysql

volumes:
    mysql:
        driver: local
